name = "cloudflare-worker-api"
main = "./dist/index.mjs"
compatibility_date = "2023-09-19"
workers_dev = true

[dev]
ip = "localhost"
port = 3000
local_protocol = "http"

[vars]
ENV = "development"
DATABASE_URL = "prisma://aws-us-east-1.prisma-data.com/?api_key=7TeQz79NEU3J3DU9DQyvr7btJBvPZ5z7o481bF1KsWxbgm0lDUeewVVzPZanLHYt"
# DATABASE_URL = "prisma://localhost?api_key=custom-token"

[build]
command = "npm run build"
