version: "3"

services:
  data-proxy:
    image: node:16-alpine3.16
    working_dir: /app
    ports:
      - "3010:3010"
    entrypoint: /app/entrypoint.sh
    command: yarn pdp
    env_file:
      - proxy.env
    environment:
      PORT: 3010
    volumes:
      - ../prisma:/app/prisma
      - ./yarn.lock:/app/yarn.lock
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./package.json:/app/package.json
      - node_modules:/app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "443:443"
    environment:
      STAGE: local
      DOMAINS: "localhost -> http://data-proxy:3010"
    volumes:
      - ssl_certs:/var/lib/https-portal

volumes:
  node_modules:
  ssl_certs:
